language: node_js

node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "iojs"

branches:
  except:
    - gh-pages

script:
  - npm test

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - CODECLIMATE_REPO_TOKEN=6351e534668c7f4a0a5b287f621e7e9231509c5a0701443f7c5071f5efae97b8 ./node_modules/codeclimate-test-reporter/bin/codeclimate.js < ./coverage/lcov.info

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5ba2780eb32dc366def2
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

